#!/usr/bin/env python
# encoding: utf-8
import limbo

def build(bld):
    libs = 'TBB EIGEN BOOST LIMBO LIBCMAES NLOPT SFERES2 BOOST_CHRONO RT SDL '

    cxxflags = bld.get_env()['CXXFLAGS']

    limbo.create_variants(bld,
                      source='cartpole.cpp',
                      includes='. ../../../../src ../ ../../include',
                      target='cartpole',
                      uselib=libs,
                      uselib_local='limbo',
                      cxxflags = cxxflags + ['-D NODSP'],
                      variants = ['SIMU', 'SIMU SPGPS', 'SIMU GPPOLICY', 'SIMU GPPOLICY SPGPS'])

    limbo.create_variants(bld,
                      source='pendulum.cpp',
                      includes='. ../../../../src ../ ../../include',
                      target='pendulum',
                      uselib=libs,
                      uselib_local='limbo',
                      cxxflags = cxxflags + ['-D NODSP'],
                      variants = ['SIMU', 'SIMU GPPOLICY', 'SIMU LINEAR'])

    if bld.env.DEFINES_SDL:
        limbo.create_variants(bld,
                        source='cartpole.cpp',
                        includes='. ../../../../src ../ ../../include',
                        target='cartpole',
                        uselib=libs,
                        uselib_local='limbo',
                        cxxflags = cxxflags,
                        variants = ['GRAPHIC', 'GRAPHIC SPGPS', 'GRAPHIC GPPOLICY', 'GRAPHIC GPPOLICY SPGPS'])
        limbo.create_variants(bld,
                        source='pendulum.cpp',
                        includes='. ../../../../src ../ ../../include',
                        target='pendulum',
                        uselib=libs,
                        uselib_local='limbo',
                        cxxflags = cxxflags,
                        variants = ['GRAPHIC', 'GRAPHIC GPPOLICY', 'GRAPHIC LINEAR'])