#!/usr/bin/env python
# encoding: utf-8
import limbo

def build(bld):
    libs = 'TBB EIGEN BOOST LIMBO LIBCMAES NLOPT SFERES2 BOOST_CHRONO RT SDL THREADS KDL TRAC_IK '
    dart_libs = 'ROBOT_DART DART BOOST_DART ' + libs
    robot_libs = dart_libs + ' LIBDYNAMIXEL'

    cxxflags = bld.get_env()['CXXFLAGS']

    limbo.create_variants(bld,
                    source='reacher.cpp',
                    includes='. ../../../../src ../ ../../include',
                    target='reacher',
                    uselib=dart_libs,
                    uselib_local='limbo',
                    variants = ['SIMU', 'SIMU MEAN', 'SIMU MEAN MODELIDENT', 'SIMU MEAN MODELIDENT ONLYMI'])

    if bld.get_env()['BUILD_GRAPHIC'] == True:
        limbo.create_variants(bld,
                          source='reacher.cpp',
                          includes='. ../../../../src ../ ../../include',
                          target='reacher',
                          uselib='DART_GRAPHIC '+dart_libs,
                          uselib_local='limbo',
                          variants = ['GRAPHIC', 'GRAPHIC MEAN', 'GRAPHIC MEAN MODELIDENT', 'GRAPHIC MEAN MODELIDENT ONLYMI'])
    
    if bld.get_env()['BUILD_ROBOT'] == True:
        limbo.create_variants(bld,
                          source='reacher.cpp',
                          includes='. ../../../../src ../ ../../include',
                          target='reacher',
                          uselib=robot_libs,
                          uselib_local='limbo',
                          variants = ['ROBOT', 'ROBOT MEAN', 'ROBOT MEAN MODELIDENT', 'ROBOT MEAN MODELIDENT ONLYMI'])

    if bld.get_env()['BUILD_ROBOT'] == True and bld.env.DEFINES_ROS:
        limbo.create_variants(bld,
                          source='door_robot.cpp',
                          includes='. ../../../../src ../ ../../include',
                          target='door_robot',
                          uselib='ROS '+robot_libs,
                          uselib_local='limbo',
                          variants = ['ROBOT', 'ROBOT MEAN', 'ROBOT MEAN MODELIDENT', 'ROBOT MEAN MODELIDENT ONLYMI'])
