#!/usr/bin/env python
# encoding: utf-8
import limbo
import glob

def build(bld):
    dart_libs = 'TBB EIGEN BOOST LIMBO LIBCMAES NLOPT SFERES2 BOOST_CHRONO RT ROBOT_DART DART BOOST_DART THREADS '
    dart_libs_graphic = dart_libs + 'DART_GRAPHIC'

    path = bld.path.abspath()[:-len('src/dart')] + 'res'

    if 'INCLUDES_ROBOT_DART' not in bld.get_env() or 'INCLUDES_DART' not in bld.get_env():
        Logs.pprint('YELLOW', 'Dart or robot_dart not found in your system. Will not build DART scenarios')
        return

    cxxflags = bld.get_env()['CXXFLAGS']
    
    limbo.create_variants(bld,
                      source='simple_arm.cpp',
                      includes='. ../../../../src ../ ../../include',
                      target='simple_arm',
                      uselib=dart_libs,
                      uselib_local='limbo',
                      cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                      variants = ['SIMU'])

    if bld.get_env()['BUILD_GRAPHIC'] == True:
        limbo.create_variants(bld,
                          source='simple_arm.cpp',
                          includes='. ../../../../src ../ ../../include',
                          target='simple_arm',
                          uselib=dart_libs_graphic,
                          uselib_local='limbo',
                          cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                          variants = ['GRAPHIC'])

    # Find new targets
    files = glob.glob(bld.path.abspath()+"/*.cpp")
    new_targets = []
    for f in files:
        target_name = f[f.rfind('/')+1:-4]
        # Ignore our sample scenarios
        if target_name != 'simple_arm':
            new_targets.append(target_name)

    # Compile new targets
    for target in new_targets:
        limbo.create_variants(bld,
                        source=target+'.cpp',
                        includes='. ../../../../src ../ ../../include',
                        target=target,
                        uselib=dart_libs,
                        uselib_local='limbo',
                        cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                        variants = ['SIMU'])

        if bld.get_env()['BUILD_GRAPHIC'] == True:
            limbo.create_variants(bld,
                            source=target+'.cpp',
                            includes='. ../../../../src ../ ../../include',
                            target=target,
                            uselib=dart_libs_graphic,
                            uselib_local='limbo',
                            cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                            variants = ['GRAPHIC'])