#!/usr/bin/env python
# encoding: utf-8
import limbo

def build(bld):
    dart_libs = 'TBB EIGEN BOOST LIMBO LIBCMAES NLOPT SFERES2 BOOST_CHRONO RT ROBOT_DART DART BOOST_DART THREADS '
    dart_libs_graphic = dart_libs + 'DART_GRAPHIC'

    path = bld.path.abspath()[:-len('src/dart')] + 'res'

    if 'INCLUDES_ROBOT_DART' not in bld.get_env() or 'INCLUDES_DART' not in bld.get_env():
        Logs.pprint('YELLOW', 'Dart or robot_dart not found in your system. Will not build DART scenarios')
        return

    cxxflags = bld.get_env()['CXXFLAGS']
    
    limbo.create_variants(bld,
                      source='simple_arm.cpp',
                      includes='. ../../../../src ../ ../../include',
                      target='simple_arm',
                      uselib=dart_libs,
                      uselib_local='limbo',
                      cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                      variants = ['SIMU'])

    if bld.get_env()['BUILD_GRAPHIC'] == True:
        limbo.create_variants(bld,
                          source='simple_arm.cpp',
                          includes='. ../../../../src ../ ../../include',
                          target='simple_arm',
                          uselib=dart_libs_graphic,
                          uselib_local='limbo',
                          cxxflags = cxxflags + ['-DRESPATH="' + path + '"'],
                          variants = ['GRAPHIC'])